site:
  name: Sylvan Lake AUTOPRO
  site: 'https://sylvanlakeautopro.com'
  base: '/'
  trailingSlash: false

metadata:
  title:
    default: Sylvan Lake AUTOPRO
    template: '%s | Sylvan Lake AUTOPRO'
  description: "Trusted auto repair in Sylvan Lake since 2006. ASE-certified mechanics, NAPA Peace of Mind warranty. Inspections, brakes, diagnostics & more. Call (403) 887-0440."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Sylvan Lake AUTOPRO
    images:
      - url: '~/assets/images/og-image.png'
        width: 1200
        height: 630
    type: website
  twitter:
    handle: '@sylvanlakeauto'
    site: '@sylvanlakeauto'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: false
    postsPerPage: 6
    post:
      isEnabled: true
      permalink: '/%slug%'
      robots:
        index: true
    list:
      isEnabled: true
      pathname: 'blog'
      robots:
        index: true
    category:
      isEnabled: true
      pathname: 'category'
      robots:
        index: true
    tag:
      isEnabled: true
      pathname: 'tag'
      robots:
        index: false
    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: 'system'